version: '3.8'

services:
  foss-vital:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
      - CACHE_TTL=300000
      - CACHE_MAX_SIZE=1000
      # Uncomment and set your GitHub token for higher rate limits
      # - GITHUB_TOKEN=your_github_token_here
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/health').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - foss-vital
  #   restart: unless-stopped
