name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run code quality checks
      run: npm run check

    - name: Build project
      run: npm run build

    - name: Test build output
      run: |
        ls -la dist/
        node -e "console.log('Build successful!')"

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        echo "FROM node:20-alpine" > Dockerfile
        echo "WORKDIR /app" >> Dockerfile
        echo "COPY package*.json ./" >> Dockerfile
        echo "RUN npm ci --only=production" >> Dockerfile
        echo "COPY dist/ ./dist/" >> Dockerfile
        echo "EXPOSE 3000" >> Dockerfile
        echo "CMD [\"npm\", \"start\"]" >> Dockerfile
        docker build -t foss-vital:latest .
        
    - name: Test Docker image
      run: |
        docker run --rm foss-vital:latest node -e "console.log('Docker build successful!')"
